version: '3.3'

services:
  redis:
    image: redis
    restart: always
    container_name: 'redis'
    command: redis-server
    working_dir: /data
    volumes:
      - redis-data:/data
      - /etc/localtime:/etc/localtime
    ports:
      - 6379:6379

  flower:
    image: mher/flower
    env_file:
      - ./.env
    ports:
      - 5555:5555

volumes:
  redis-data:
