version: '3.3'

services:
  bot:
    restart: always
    build:
      context: .
    entrypoint:
      - /usr/app/bot_entrypoint.sh
    volumes:
      - /logs/bot_logs:/usr/app/logs
    env_file:
      - .env

  celery:
    restart: always
    build:
      context: .
    command: celery -A src.worker.tasks.app worker -B -E
    volumes:
      - /logs/celery_logs:/usr/app/logs
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis
    restart: always
    container_name: 'redis'
    command: redis-server
    working_dir: /data
    volumes:
      - redis-data:/data
      - /etc/localtime:/etc/localtime
    expose:
      - 6379

  flower:
    image: mher/flower
    env_file:
      - .env
    ports:
      - 5555:5555

volumes:
  redis-data:
