version: '3.3'

services:
  bot:
    restart: always
    build:
      context: .
    entrypoint:
      - /usr/app/bot_entrypoint.sh
    volumes:
      - ./bot_logs:/usr/app/logs
    depends_on:
      - db
    env_file:
      - .env

  celery:
    restart: always
    build:
      context: .
    command: celery -A src.worker.tasks.app worker -B -E
    volumes:
      - ./celery_logs:/usr/app/logs
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    ports:
      - 5432:5432

  redis:
    image: redis
    restart: always
    container_name: 'redis'
    command: redis-server
    working_dir: /data
    volumes:
      - redis-data:/data
      - /etc/localtime:/etc/localtime
    ports:
      - 6379:6379

  flower:
    image: mher/flower
    env_file:
      - .env
    ports:
      - 5555:5555

volumes:
  redis-data:
  postgres_data:
