apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: registry.gitlab.com/ra1ze505/mailing_bot:develop
          imagePullPolicy: Always
          command:
            - "/usr/app/bot_entrypoint.sh"
          envFrom:
            - secretRef:
                name: env-config-dev
          volumeMounts:
            - name: bot-logs
              mountPath: /usr/app/logs
      imagePullSecrets:
        - name: gitlab-registry
      volumes:
        - name: bot-logs
          emptyDir: {}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mailing-cronjob-dev
spec:
  # Каждую минуту
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: crons
              image: registry.gitlab.com/ra1ze505/mailing_bot:develop
              command: ["python", "-m", "src.worker.crons", "-n", "mailing"]
              envFrom:
                - secretRef:
                    name: env-config-dev
              volumeMounts:
                - name: cron-logs
                  mountPath: /usr/app/logs
          restartPolicy: OnFailure
          volumes:
            - name: cron-logs
              emptyDir: {}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: parse-cronjob-dev
spec:
  # Каждый час в 30 минут
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: crons
              image: registry.gitlab.com/ra1ze505/mailing_bot:develop
              command: ["python", "-m", "src.worker.crons", "-n", "parse"]
              envFrom:
                - secretRef:
                    name: env-config-dev
              volumeMounts:
                - name: cron-logs
                  mountPath: /usr/app/logs
          restartPolicy: OnFailure
          volumes:
            - name: cron-logs
              emptyDir: {}
